from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import os

def create_pdf(data, output_path, original_image_path):
    c = canvas.Canvas(output_path, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawString(50, height - 50, "Eye Disease Analysis Report")
    
    # Divider
    c.line(50, height - 60, width - 50, height - 60)
    
    # Patient/Scan Info (Generic)
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 90, "Scan Type: Retinal / Eye Image Analysis")
    c.drawString(50, height - 110, "Analysis Method: AI-Based Classification (Simulated)")
    
    # Images (Original vs Heatmap)
    y_img = height - 350
    img_width = 200
    img_height = 200
    
    try:
        # Original Image
        c.drawString(50, height - 140, "Original Image:")
        if os.path.exists(original_image_path):
            img = ImageReader(original_image_path)
            c.drawImage(img, 50, y_img, width=img_width, height=img_height, preserveAspectRatio=True)
            
        # Heatmap
        c.drawString(300, height - 140, "Attention Heatmap:")
        heatmap_abs_path = data.get('heatmap_path_abs') # We need absolute path here
        if heatmap_abs_path and os.path.exists(heatmap_abs_path):
            img_heat = ImageReader(heatmap_abs_path)
            c.drawImage(img_heat, 300, y_img, width=img_width, height=img_height, preserveAspectRatio=True)
            
    except Exception as e:
        c.drawString(50, y_img, f"Error loading images: {e}")

    # Results Section
    y_text = y_img - 40
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y_text, "Analysis Results")
    
    y_text -= 30
    c.setFont("Helvetica", 12)
    
    fields = [
        ("Disease Type:", data['disease_type']),
        ("Confidence Score:", data['confidence_score']),
        ("Risk Level:", data['risk_level']),
        ("Localization:", data['localization']),
    ]
    
    for label, value in fields:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, y_text, label)
        c.setFont("Helvetica", 12)
        c.drawString(200, y_text, str(value))
        y_text -= 20
        
    y_text -= 20
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y_text, "Recommendations")
    y_text -= 30
    
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y_text, "Treatment Suggestion:")
    c.setFont("Helvetica", 12)
    # Simple wrapping for long text
    treatment_text = data['treatment_suggestion']
    if len(treatment_text) > 80:
        c.drawString(50, y_text - 15, treatment_text[:80])
        c.drawString(50, y_text - 30, treatment_text[80:])
        y_text -= 40
    else:
        c.drawString(50, y_text - 15, treatment_text)
        y_text -= 40

    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y_text, "First Aid / Advice:")
    c.setFont("Helvetica", 12)
    advice_text = data['first_aid']
    c.drawString(50, y_text - 15, advice_text)
    
    # Disclaimer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "DISCLAIMER: This report is generated by an AI system and is NOT a medical diagnosis.")
    c.drawString(50, 35, "Please consult a certified ophthalmologist for professional medical advice.")
    
    c.save()
